### ISSUE TITLE
Introduction lesson link is broken

### ISSUE THREAD

**Issue by EBUJOLD** [nickcounts/Arduino-Lessons#8] opened 2017-06-07 14:42 UTC
I don't know how to fix it

**Comment by nickcounts** [comment] 2017-06-07 20:37
I like this - good use of the issues area.

Let's tag broken things with "bug" to make it easier to sort as the project moves along.
Also, while it looks like you got it sorted out, it's nice to document where the issue is - so for this one, maybe say "introduction lesson link broken in sidebar" or wherever it is.

Incidentally, the introduction lesson link is still broken in the sidebar ;)

**Comment by jtsingh7** [comment] 2017-06-08 12:01
It is now fixed. For future linking purposes, the introduction file is titled "introduction.md"

**Closed as completed** 2017-06-08 12:01 UTC
Labels: bug
